# Generated by Django 3.2 on 2026-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField()),
                ('transaction_time', models.IntegerField()),
                ('customer_age', models.IntegerField()),
                ('location_score', models.IntegerField()),
                ('previous_fraud_count', models.IntegerField()),
                ('prediction', models.CharField(max_length=20)),
            ],
        ),
    ]
